<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-86SU9N9" name="Basic.changereqdataprov" tests="1" failures="0" timestamp="2020-03-29T13:18:46 PDT" time="0.019" errors="1">
  <testcase name="createrequest" time="0.019" classname="Basic.changereqdataprov">
    <error type="org.testng.internal.reflect.MethodMatcherException" message="
[public void Basic.changereqdataprov.createrequest(java.lang.String[][])] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: createrequest([Parameter{index=0, type=[[Ljava.lang.String;, declaredAnnotations=[]}])
Arguments: [(java.lang.String) ./data1.json]">
      <![CDATA[org.testng.internal.reflect.MethodMatcherException: 
[public void Basic.changereqdataprov.createrequest(java.lang.String[][])] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: createrequest([Parameter{index=0, type=[[Ljava.lang.String;, declaredAnnotations=[]}])
Arguments: [(java.lang.String) ./data1.json]
at org.testng.internal.reflect.DataProviderMethodMatcher.getConformingArguments(DataProviderMethodMatcher.java:43)
at org.testng.internal.Parameters.injectParameters(Parameters.java:909)
at org.testng.internal.MethodRunner.runInParallel(MethodRunner.java:104)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:811)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- createrequest -->
  <system-out/>
</testsuite> <!-- Basic.changereqdataprov -->
